/**
 * github-commit.agent.js
 *
 * Replaced LlmAgent with a direct service call to avoid Gemini 64K output
 * token limit hitting mid-commit when apps have 20+ files.
 *
 * Does exactly what the agent did:
 *  1. Create GitHub repo
 *  2. Commit every file (README first, then rest)
 *  3. Return { repoUrl, filesCommitted, failedFiles, summary }
 */

const axios = require('axios');
const githubService = require('../../services/github.service');

async function runGithubCommit(payload) {
  const {
    repoName, githubOrg, branch = 'main',
    isPrivate, githubPAT, appName,
    appDescription, generatedFiles
  } = payload;

  const headers = {
    Accept: 'application/vnd.github+json',
    Authorization: `Bearer ${githubPAT}`,
    'X-GitHub-Api-Version': '2022-11-28',
  };

  // ── Step 1: Create repo ───────────────────────────────────────────────────
  let repoUrl;
  try {
    try {
      const resp = await axios.post(
        `https://api.github.com/orgs/${githubOrg}/repos`,
        { name: repoName, private: isPrivate, description: appDescription || '', auto_init: true },
        { headers }
      );
      repoUrl = resp.data.html_url;
    } catch (orgErr) {
      if (orgErr.response?.status === 404 || orgErr.response?.status === 422) {
        const resp = await axios.post(
          `https://api.github.com/user/repos`,
          { name: repoName, private: isPrivate, description: appDescription || '', auto_init: true },
          { headers }
        );
        repoUrl = resp.data.html_url;
      } else {
        throw orgErr;
      }
    }
  } catch (err) {
    const message = err.response?.data?.message || err.message;
    console.error('[GithubCommit] Failed to create repo:', message);
    return { repoUrl: null, filesCommitted: 0, failedFiles: [], error: message, summary: `Failed to create repo: ${message}` };
  }

  console.log(`[GithubCommit] Repo created: ${repoUrl}`);

  // ── Step 2: Sort files — README first, then config, then source ───────────
  const files = generatedFiles?.files || [];
  const sorted = [
    ...files.filter(f => f.path === 'README.md'),
    ...files.filter(f => f.path !== 'README.md' && isConfigFile(f.path)),
    ...files.filter(f => f.path !== 'README.md' && !isConfigFile(f.path)),
  ];

  // ── Step 3: Commit every file ─────────────────────────────────────────────
  const failedFiles = [];
  let filesCommitted = 0;
  const commitMessage = `🚀 Generated by ACP — initial scaffold for ${appName}`;

  for (const file of sorted) {
    try {
      await githubService.commitFile(repoUrl, file.path, file.content, commitMessage, branch, githubPAT);
      filesCommitted++;
      console.log(`[GithubCommit] Committed (${filesCommitted}/${sorted.length}): ${file.path}`);
    } catch (err) {
      const error = err.response?.data?.message || err.message;
      console.error(`[GithubCommit] Failed to commit ${file.path}:`, error);
      failedFiles.push({ path: file.path, error });
    }
  }

  return {
    repoUrl,
    filesCommitted,
    failedFiles,
    summary: `Successfully created repo and committed ${filesCommitted} of ${sorted.length} files via ACP Portal`,
  };
}

function isConfigFile(path) {
  return (
    path.endsWith('.json') ||
    path.endsWith('.yml') ||
    path.endsWith('.yaml') ||
    path.endsWith('.env') ||
    path.endsWith('.gitignore') ||
    path.endsWith('Dockerfile') ||
    path.endsWith('.example')
  );
}

module.exports = { runGithubCommit };